language: ruby
bundler_args: --without local_development
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - rbx-2
notifications:
  recipients:
    - timo.roessner@googlemail.com
    - matijs@matijs.net
    - emil.rehnberg@gmail.com
  irc: "irc.freenode.org#reek"
